<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>2.0.2</Version>
    <OutputPath>bin\$(Configuration)\SPT\user\mods\$(ProjectName)\$(AssemblyName)\</OutputPath>
    <PreserveCompilationContext>false</PreserveCompilationContext>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <GenerateDependencyFile>false</GenerateDependencyFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SPTarkov.Common" Version="4.0.0" />
    <PackageReference Include="SPTarkov.DI" Version="4.0.0" />
    <PackageReference Include="SPTarkov.Reflection" Version="4.0.0" />
    <PackageReference Include="SPTarkov.Server.Core" Version="4.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="bundles\**">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include=".\bundles.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="config\**">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="db\**">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="LICENSE">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="README.md">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
